name "build"
on:
  push:
    branches:
      - main
    pull_request:

jobs:
  build_jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # setup make (expected?)
      # setup JDK (openjdk?)
      - uses: actions/setup-java@v2
        with:
        distribution: 'temurin'
        java-version: '17'
      
      - name: build
        run: |
          make tarball
